//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstKPMG_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int iProductId { get; set; }
        public string vchProductName { get; set; }
        public string vchProductCategory { get; set; }
        public Nullable<decimal> decproductPrice { get; set; }
        public Nullable<System.DateTime> dtPurchaseDate { get; set; }
    }
}
