//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstKPMG_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserLoginDetail
    {
        public int iUserId { get; set; }
        public string vchUserName { get; set; }
        public string vchUserPassword { get; set; }
        public string vchUserRole { get; set; }
    }
}
